#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 17 01:07:17 2019

@author: vikasmittal
"""

# quick sort

qlist = [7,4,6,18,8]

i=0 # represents the starting index of the list
k=4 # represents the end index of the list

midpoint = int(i + (k-i)/2) # finding mid index to calculate pivot for the list

pivot = qlist[midpoint]

print(pivot)

#defining l and h as pointers for list traversal
l =i 
h = k

done=False

while(done==False):
    while(qlist[l]<pivot):
        l+=1
    
    while(qlist[h] > pivot):
        h-=1
    
    if(l>=h):
        done=True
    else:
        temp = qlist[l]
        qlist[l] = qlist[h]
        qlist[h] = temp
        l+=1
        h-=1
        
print(h)

# the complexity of quick sort is N.logN
